name: stvr_mobile
description: STVR LiveTV - Streaming aplikÃ¡cia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.0
  wakelock_plus: ^1.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/splash/

flutter_native_splash:
  color: "#1e3a8a"
  image: assets/splash/splash.png
  android_branding: assets/icons/ic_launcher_192.png
